[FE]Feat/#119
UMC-FITple/Frontend pull request #124
Opened 2024-08-28 12:59 UTC by chundang

## 💻 Feature 설명
> 디테일 디자인 재수정 inline제거
<br>

## 📝 To-do
**메인주제**
- [ ] 할 일
- [x] 끝난 일
- [x] detail page 디자인 재수정
<br>

2024-08-28 12:59 UTC, chundang commented
디테일 부분 inline제거하고 디자인 수정했습니다!

2024-08-29 05:16 UTC, yeon-dong commented
![image](https://github.com/user-attachments/assets/87b2b8c6-e4f7-4dba-ab17-4cb24c797757)
@chundang 이 부분 안된 것 같아요

2024-08-29 05:16 UTC, yeon-dong requested changes
![image](https://github.com/user-attachments/assets/44acc8e2-a18e-4840-89d7-4ffee03344c0)

2024-08-29 07:41 UTC, chundang commented
![Uploading 수정삭제.jpg…]()

2024-09-03 08:23 UTC, yeon-dong approved these changes

2024-09-03 08:24 UTC, merged